# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a92a377b1fe973659aa4033c11baffadd2fe520dff0134379b0fb746bac9551fe74f87401ab2d5c2307f49341a8cfea30ed8bc28d7826c70702b64ccb1a135e

test:
  secret_key_base: c302b4658ba1d7e9297805efa7e00cd6f9c7aab26ccb1f8d5792f29c7fb2e12864a72424e553380bd22a7e6acbefbb4a27a7b67837335e54fb0856c7569f0e0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
